name: Build and Deploy Dioxus Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Rust toolchain
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # Install cargo-binstall for precompiled CLI
      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      # Install the pinned Dioxus CLI version using binstall for pre-compiled binaries
      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli@0.6.3 -y


      - name: Build and deploy to GitHub Pages
        run: bash ./deploy.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          publish_branch: gh-pages
